import "./globals.css";
import type { Metadata } from "next";
import { CssBaseline, ThemeProvider } from "@mui/material";
import { theme } from "../theme";

import { plusJakarta } from "@/utils/fonts";
import { Providers } from "@/redux/providers";
import { AOSInit } from "@/components";


export const metadata: Metadata = {
  title: "Knights Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AOSInit />
      <body className={`${plusJakarta.className}`}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <Providers>{children}</Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
