export const databaseData = [
  {
    id: "1",
    name: "John Doe",
    stats: ["stats 1", "stats 2", "stats 3", "stats 4"],
    image: "/images/database-player1.jpg",
    rank: "12",
    position: "Center",
    height: "152.4cm",
    weight: "50kg",
    offDef: "defence",
    exercises: ["Vertical", "3 Cone"],
    coachNotes:
      "John has great speed and lateral thinking would be a great addition to any team.",
    bio: "Hi Im John and a QB from the knights academy and I wish to become a professional football player",
    education: "",
    fourtyYard: "4.45",
    twentyYard: "2.23",
    verticalJump: '40.5"',
    broadJump: '10.5"',
    threeCone: "6.9",
    bench: "20 Reps",
    rating: 1.5,
    videos: ["/videos/video1.mp4", "/videos/video2.mp4", "/videos/video3.mp4"],
    featuredVideo: "/videos/video3.mp4",
  },
  {
    id: "2",
    name: "Jane Smith",
    stats: ["stats 1", "stats 2", "stats 3"],
    image: "/images/database-player2.jpg",
    rank: "6",
    position: "Quarterback",
    height: "165.1cm",
    weight: "55kg",
    offDef: "offense",
    exercises: ["Split", "Dash", "Shuttle", "Bench"],
    coachNotes:
      "Jane has good speed and lateral thinking would be a great addition to any team.",
    bio: "Hi, I'm Jane, a QB from the knights academy, and I aspire to become a professional football player",
    education: "Bachelor's in Physical Education",
    fourtyYard: "4.55",
    twentyYard: "2.30",
    verticalJump: '38.5"',
    broadJump: '11.0"',
    threeCone: "7.1",
    bench: "18 Reps",
    rating: 2.5,
    videos: [],
    featuredVideo: "",
  },
  {
    id: "3",
    name: "Mike Johnson",
    stats: ["stats 1", "stats 2", "stats 3"],
    image: "/images/database-player3.jpg",
    rank: "9",
    position: "Wide Receiver",
    height: "175.3cm",
    weight: "60kg",
    offDef: "offense",
    exercises: ["Split", "Dash", "Shuttle", "Bench"],
    coachNotes:
      "Mike has great speed and lateral thinking would be a great addition to any team.",
    bio: "Hello, I'm Mike, a wide receiver with a passion for making big plays on the field",
    education: "High School Graduate",
    fourtyYard: "4.40",
    twentyYard: "2.20",
    verticalJump: '42.0"',
    broadJump: '10.8"',
    threeCone: "6.8",
    bench: "15 Reps",
    rating: 0.5,
    videos: ["/videos/video1.mp4", "/videos/video2.mp4", "/videos/video3.mp4"],
    featuredVideo: "/videos/video3.mp4",
  },
  {
    id: "4",
    name: "John Cena",
    stats: ["stats 1", "stats 2", "stats 3"],
    image: "/images/database-player4.jpg",
    rank: "15",
    position: "Defensive End",
    height: "190.5cm",
    weight: "120kg",
    offDef: "defence",
    exercises: ["Dash", "Shuttle"],
    bio: "I'm John Cena, a defensive tackle known for my strength and agility on the field",
    coachNotes:
      "John has great speed and lateral thinking would be a great addition to any team.",
    education: "Bachelor's in Business Administration",
    fourtyYard: "5.00",
    twentyYard: "2.50",
    verticalJump: '34.5"',
    broadJump: '9.8"',
    threeCone: "7.5",
    bench: "25 Reps",
    rating: 5,
    videos: ["/videos/video1.mp4", "/videos/video2.mp4", "/videos/video3.mp4"],
    featuredVideo: "/videos/video3.mp4",
  },
  {
    id: "5",
    name: "David Wilson",
    stats: ["stats 1", "stats 2", "stats 3"],
    image: "/images/database-player5.jpg",
    rank: "8",
    position: "Safety",
    height: "167.6cm",
    weight: "80kg",
    offDef: "offense",
    exercises: ["Dash"],
    bio: "I'm David Wilson, a running back with a passion for breaking tackles and scoring touchdowns",
    coachNotes:
      "David has great speed and lateral thinking would be a great addition to any team.",
    education: "Bachelor's in Sports Management",
    fourtyYard: "4.60",
    twentyYard: "2.35",
    verticalJump: '36.5"',
    broadJump: '10.0"',
    threeCone: "7.0",
    bench: "17 Reps",
    rating: 3,
    videos: ["/videos/video1.mp4", "/videos/video2.mp4", "/videos/video3.mp4"],
    featuredVideo: "/videos/video1.mp4",
  },
  {
    id: "6",
    name: "Jane Smith",
    stats: ["stats 1", "stats 2", "stats 3"],
    image: "/images/database-player2.jpg",
    rank: "10",
    position: "Cornerback",
    height: "170.2cm",
    weight: "70kg",
    offDef: "defence",
    exercises: ["Dash", "Shuttle"],
    coachNotes:
      "Jane has great speed and lateral thinking would be a great addition to any team.",
    bio: "Hey, I'm Jane Smith, a cornerback with exceptional speed and coverage skills",
    education: "Bachelor's in Communication",
    fourtyYard: "4.42",
    twentyYard: "2.25",
    verticalJump: '39.2"',
    broadJump: '10.2"',
    threeCone: "6.7",
    bench: "16 Reps",
    rating: 4,
    videos: ["/videos/video1.mp4", "/videos/video2.mp4", "/videos/video3.mp4"],
    featuredVideo: "/videos/video1.mp4",
  },
  {
    id: "7",
    name: "Mike Johnson",
    stats: ["stats 1", "stats 2", "stats 3"],
    image: "/images/database-player3.jpg",
    rank: "11",
    position: "Linebacker",
    height: "185.4cm",
    weight: "95kg",
    offDef: "defence",
    exercises: ["Shuttle"],
    bio: "Hello, I'm Mike Johnson, a linebacker known for my ability to read offenses and make crucial tackles",
    coachNotes:
      "Mike has great speed and lateral thinking would be a great addition to any team.",
    education: "Bachelor's in Criminal Justice",
    fourtyYard: "4.60",
    twentyYard: "2.40",
    verticalJump: '37.8"',
    broadJump: '10.5"',
    threeCone: "7.0",
    bench: "19 Reps",
    rating: 1,
    videos: ["/videos/video1.mp4", "/videos/video2.mp4", "/videos/video3.mp4"],
    featuredVideo: "/videos/video2.mp4",
  },
  {
    id: "8",
    name: "Emily Davis",
    stats: ["stats 1", "stats 2", "stats 3"],
    image: "/images/database-player4.jpg",
    rank: "14",
    position: "Kicker",
    height: "160.0cm",
    weight: "65kg",
    offDef: "defence",
    exercises: ["Broad"],
    bio: "Hi, I'm Emily Davis, a kicker with a knack for making clutch field goals",
    coachNotes:
      "Emily has great speed and lateral thinking would be a great addition to any team.",
    education: "Bachelor's in Physics",
    fourtyYard: "5.20",
    twentyYard: "2.60",
    verticalJump: '33.0"',
    broadJump: '9.0"',
    threeCone: "7.5",
    bench: " ",
    rating: 4.5,
    videos: ["/videos/video1.mp4", "/videos/video2.mp4", "/videos/video3.mp4"],
    featuredVideo: "/videos/video1.mp4",
  },
  {
    id: "9",
    name: "David Wilson",
    stats: ["stats 1", "stats 2", "stats 3"],
    image: "/images/database-player5.jpg",
    rank: "1",
    position: "Safety",
    height: "167.6cm",
    weight: "80kg",
    offDef: "offense",
    exercises: ["Dash"],
    bio: "I'm David Wilson, a running back with a passion for breaking tackles and scoring touchdowns",
    coachNotes: "David is a great player.",
    education: "Bachelor's in Sports Management",
    fourtyYard: "4.60",
    twentyYard: "2.35",
    verticalJump: '36.5"',
    broadJump: '10.0"',
    threeCone: "7.0",
    bench: "17 Reps",
    rating: 2,
    videos: ["/videos/video1.mp4", "/videos/video2.mp4", "/videos/video3.mp4"],
    featuredVideo: "/videos/video1.mp4",
  },
];

